### ISSUE TITLE
Splatalyzer app

### ISSUE THREAD

**Issue by zhxie** [cengelbart39/Splatalyzer#1]
I am so impressed by the package and valued your work.

Although I think people do not often analyze their builds and just copy one from the sendou.ink showcase, it would be so cool to be able to analyze builds directly on iPhone.

Do you have any plan to release an app of Splatalyzer?

**Comment by cengelbart39** [comment]
Thanks. I really appreciate it.

Definitely more of a "for fun" project than anything. I don't really expect people to actually use this that much, if at all.

I don't really have plans to release it as an app. Honestly, it probably wouldn't be that much work since I'm providing views in SplatalyzerUI. I also want to get around to improving what I've provided so far in terms of UI elements, especially getting them all to look good across all supported platforms.

I guess the answer, is maybe, but I don't have any immediate plans for it.
